name: 'SimpleCov Check Action'
description: 'Enabling SimpleCov support for Github Actions'
author: 'Josh Frankel'
inputs:
  github_token:
    description: "Github token for create checks"
    required: true
  coverage_path:
    description: 'File path to coverage results'
    default: "coverage/.last_run.json"
  minimum_coverage:
    description: 'Percentage required to pass'
    default: 90
  minimum_coverage_type:
    description: 'The type of coverage: line or branch'
    default: "line"
  debug:
    description: 'Display logs for debugging'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
